name: contactcars_app_retail
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
 
version: 6.5.5+1
build: 1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  animated_bottom_navigation_bar: ^1.3.0
  app_links: ^4.0.1
  avatar_stack: ^1.2.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  pretty_dio_logger: ^1.3.1
  readmore: ^2.1.0
  rxdart: ^0.27.7
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  country_icons: ^3.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  dio: ^5.3.2
  dio_http_formatter: ^3.2.0
  dotted_border: ^2.1.0
  easy_localization: ^3.0.3
  editable: ^2.0.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_analytics: ^10.10.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.15
  firebase_messaging: ^14.7.15
  firebase_performance: ^0.9.3+4
  firebase_remote_config: ^4.3.4
  flutter_advanced_switch: ^3.0.1
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  geolocator: ^10.1.0
  get_it: ^7.6.4
  go_router: ^14.1.3
  google_mobile_ads: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ui: ^1.0.14
  image_picker: ^1.0.7
  instagram_bottom_nav_bar: ^3.0.5
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  loading_btn: ^1.0.3
  lottie: ^2.7.0
  multi_image_picker_view: ^1.0.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  pinput: ^4.0.0
  awesome_notifications: ^0.8.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  social_auth_btn_kit: ^0.1.1
  stop_watch_timer: ^3.0.2
  toastification: ^1.1.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.3
  uuid: ^4.0.0
  version: ^3.0.2
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2
  youtube_player_flutter: ^8.1.2
  flutter_hooks: ^0.20.5
  retry: ^3.1.2
  flutter_internet_speed_test: ^1.0.1
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  image_path_ios: "assets/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translation/

  fonts:
    - family: ibm_plex_sans_arabic_regular
      fonts:
        - asset: fonts/ibm_plex_sans_arabic_regular.ttf

    - family: ibm_plex_sans_arabic_semi_bold
      fonts:
        - asset: fonts/ibm_plex_sans_arabic_semi_bold.ttf

    - family: ibm_plex_sans_arabic_bold
      fonts:
        - asset: fonts/ibm_plex_sans_arabic_bold.ttf

    - family: ibm_plex_sans_arabic_thin
      fonts:
        - asset: fonts/ibm_plex_sans_arabic_thin.ttf

    - family: ibm_plex_sans_arabic_light
      fonts:
        - asset: fonts/ibm_plex_sans_arabic_light.ttf

    - family: ibm_plex_sans_arabic_extra_light
      fonts:
        - asset: fonts/ibm_plex_sans_arabic_extra_light.ttf

    - family: ibm_plex_sans_arabic_medium
      fonts:
        - asset: fonts/ibm_plex_sans_arabic_medium.ttf
